microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-pagopa-payments
    tag: develop-latest
    pullPolicy: Always

  ingress:
    host: "hub.internal.dev.p4pa.pagopa.it"

  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"

  autoscaling:
    enable: false

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    ENV: "DEV"
    JAVA_TOOL_OPTIONS: "-Xms384m -Xmx384m -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

    APP_PAGOPA_PAYMENTS_WS_BASE_URL: "https://api.dev.p4pa.pagopa.it/payhub"
    PAGOPA_NODE_ACA_BASE_URL: "https://api.uat.platform.pagopa.it"
  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
  keyvault:
    name: "p4pa-d-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"