microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-workflow-hub
    tag: v1.0.0
    pullPolicy: Always

  ingress:
    host: "hub.internal.p4pa.pagopa.it"

  resources:
    requests:
      memory: "1Gi"
      cpu: "750m"
    limits:
      memory: "1Gi"
      cpu: "750m"

  autoscaling:
    enable: false

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    ENV: "PROD"
    JAVA_TOOL_OPTIONS: "-Xms896m -Xmx896m -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

    JWT_TOKEN_AUDIENCE: "piattaformaunitaria.pagopa.it"
    JWT_EXTERNAL_TOKEN_ISS: "https://selfcare.pagopa.it"
    JWT_EXTERNAL_TOKEN_BASE_URL: "https://selfcare.pagopa.it"
  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
  keyvault:
    name: "p4pa-p-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

postman-test:
  run: true
  repoName: p4pa-workflow-hub
  dir: postman
  collectionName: "p4pa-workflow-hub-E2E.postman_collection.json"
  envVariablesFile: "p4pa_PROD.postman_environment.json" #inside azdo secure files
