microservice-chart:
  namespace: "payhub"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  ingress:
    create: true
    path: /p4paauth/(.*)
    host: "hub.internal.dev.p4pa.pagopa.it"

  resources:
    requests:
      memory: "512Mi"
      cpu: "150m"
    limits:
      memory: "512Mi"
      cpu: "150m"

  autoscaling:
    enable: false

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    ENV: "DEV"
    JAVA_TOOL_OPTIONS: "-Xms384m -Xmx384m -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

    JWT_TOKEN_AUDIENCE: "dev.piattaformaunitaria.pagopa.it"
    JWT_EXTERNAL_TOKEN_ISS: "https://dev.selfcare.pagopa.it"
    JWT_EXTERNAL_TOKEN_BASE_URL: "https://dev.selfcare.pagopa.it"

    APPLICATIONINSIGHTS_ROLE_NAME: "p4paauth"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"

    ENABLE_AUDIT_APPENDER: "TRUE"

    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"

    JWT_TOKEN_EXPIRATION_SECONDS: "14400" # 4 HOURS
    ACCESS_ORGANIZATION_MODE_ENABLED: "true"

  envSecret:
    JWT_TOKEN_PRIVATE_KEY: jwt-private-key
    JWT_TOKEN_PUBLIC_KEY: jwt-public-key

    REDIS_HOST: cache-standalone-host
    REDIS_PASSWORD: cache-password
    MONGODB_URI: mongodb-connection-string

    MYPAY_DB_HOST: db-host
    MYPAY_DB_USER: db-mypay-login-username
    MYPAY_DB_PASSWORD: db-mypay-login-password

    MYPIVOT_DB_HOST: db-host
    MYPIVOT_DB_USER: db-mypay-login-username
    MYPIVOT_DB_PASSWORD: db-mypay-login-password

    DATA_CIPHER_P4PA_AUTH_HASH_KEY: p4pa-auth-hash-key
    DATA_CIPHER_P4PA_AUTH_ENCRYPT_PSW: p4pa-auth-encrypt-psw

    PIATTAFORMA_UNITARIA_CLIENT_SECRET: piattaforma-unitaria-client-secret
  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
