apiVersion: v2
name: payhub-three-color
description: An example application with Java spring boot
type: application
version: 1.1.1
appVersion: 1.1.1
dependencies:
- name: microservice-chart
  version: 7.3.1
  repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
