microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-pagopa-payments
    tag: v1.0.0
    pullPolicy: Always

  ingress:
    host: "hub.internal.p4pa.pagopa.it"

  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"

  autoscaling:
    enable: false

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    ENV: "PROD"
    JAVA_TOOL_OPTIONS: "-Xms896m -Xmx896m -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

    PAGOPA_PAYMENTS_WSDL_BASE_URL: "https://hub.internal.p4pa.pagopa.it/p4papagopapayments"
    PAGOPA_NODE_ACA_BASE_URL: "https://api.platform.pagopa.it/aca/v1"
    APP_NODE_FOR_PA_URL: "https://api.platform.pagopa.it/nodo-auth/node-for-pa/v1"
    PAGOPA_TAXONOMIES_BASE_URL: "https://api.platform.pagopa.it/taxonomy/service/v1/taxonomy"
  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
  keyvault:
    name: "p4pa-p-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
