microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-pagopa-payments
    tag: uat-latest
    pullPolicy: Always

  ingress:
    host: "hub.internal.uat.p4pa.pagopa.it"

  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"

  autoscaling:
    enable: false

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    ENV: "UAT"
    JAVA_TOOL_OPTIONS: >-
      -XX:InitialRAMPercentage=60.0
      -XX:MaxRAMPercentage=70.0
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=200
      -XX:+UseContainerSupport
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=4
      -javaagent:/app/applicationinsights-agent.jar
      -agentlib:jdwp=transport=dt_socket,server=y,address=*:8001,suspend=n
      -Dcom.sun.management.jmxremote
      -Dcom.sun.management.jmxremote.port=3002
      -Dcom.sun.management.jmxremote.rmi.port=3003
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false
      -Dcom.sun.management.jmxremote.local.only=false
      -XX:+ShowCodeDetailsInExceptionMessages
      -XX:+EnableDynamicAgentLoading
      -Dspring.profiles.active=dev

    PAGOPA_PAYMENTS_WSDL_BASE_URL: "https://hub.internal.uat.p4pa.pagopa.it/p4papagopapayments"
    PAGOPA_NODE_ACA_BASE_URL: "https://api.uat.platform.pagopa.it/aca/v1"
    PAGOPA_NODE_GPD_BASE_URL: "https://api.uat.platform.pagopa.it/gpd/debt-positions-service/v1/"
    APP_NODE_FOR_PA_URL: "https://api.uat.platform.pagopa.it/nodo-auth/node-for-pa/v1"
    PAGOPA_TAXONOMIES_BASE_URL: "https://api.platform.pagopa.it/taxonomy/service/v1/taxonomy"
  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
  keyvault:
    name: "p4pa-u-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
