microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-send-notification
    tag: uat-latest
    pullPolicy: Always

  ingress:
    host: "hub.internal.uat.p4pa.pagopa.it"

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1536Mi"
      cpu: "1500m"

  autoscaling:
    enable: false

  envConfig:
    ENV: "UAT"
    SEND_BASE_URL: "https://api.uat.notifichedigitali.it"
    FILESHARE_PUBLIC_BASE_URL: "https://api.uat.p4pa.pagopa.it/fileshare"

    JAVA_TOOL_OPTIONS: >-
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=4
      -XX:InitialRAMPercentage=60.0
      -XX:MaxRAMPercentage=70.0
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=200
      -XX:+UseContainerSupport
      -XX:+ShowCodeDetailsInExceptionMessages
      -XX:+EnableDynamicAgentLoading
      -Dspring.profiles.active=dev
      -agentlib:jdwp=transport=dt_socket,server=y,address=*:8001,suspend=n
      -Dcom.sun.management.jmxremote
      -Dcom.sun.management.jmxremote.port=3002
      -Dcom.sun.management.jmxremote.rmi.port=3003
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false
      -Dcom.sun.management.jmxremote.local.only=false
      -Djava.rmi.server.hostname=127.0.0.1 
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json 

  keyvault:
    name: "p4pa-u-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"