microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-debt-positions
    tag: v1.0.0
    pullPolicy: Always

  ingress:
    host: "hub.internal.p4pa.pagopa.it"

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  autoscaling:
    enable: false
  #    minReplica: 1
  #    maxReplica: 1
  #    pollingInterval: 30 # seconds
  #    cooldownPeriod: 300 # seconds
  #    triggers:
  #      - type: cpu
  #        metadata:
  #          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
  #          value: "70"

  envConfig:
    ENV: "PROD"
    JAVA_OPTS: >-
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=100
      -XX:+UseContainerSupport
      -XX:ActiveProcessorCount=$(nproc)
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=$[$(nproc)*2]
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/secrets/appinsights.json
      -Dcom.sun.management.jmxremote.local.only=true
      -Dcom.sun.management.jmxremote.port=3002
      -Dcom.sun.management.jmxremote.authenticate=true
      -Dcom.sun.management.jmxremote.ssl=true
      -Dcom.sun.management.jmxremote.access.file=/etc/jmx/jmx.access
      -Dcom.sun.management.jmxremote.password.file=/etc/jmx/jmx.password
      -XX:+ExitOnOutOfMemoryError
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/var/log/heapdump-${POD_NAME}.hprof
      -Xlog:gc*,safepoint:file=/var/log/gc-${POD_NAME}.log:time,uptime,level,tags:filesize=100M,filecount=5
      -XX:+PerfDisableSharedMem
      -XX:+AlwaysPreTouch
      -XX:+UseTransparentHugePages
      -XX:NativeMemoryTracking=detail
      -Djdk.nio.maxCachedBufferSize=262144
      -Djava.security.egd=file:/dev/./urandom
      -Dspring.profiles.active=prod

  keyvault:
    name: "p4pa-p-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

postman-test:
  run: true
  repoName: p4pa-debt-positions
  dir: postman
  collectionName: "p4pa-debt-positions-E2E.postman_collection.json"
  envVariablesFile: "p4pa_PROD.postman_environment.json" #inside azdo secure files