microservice-chart:
  namespace: "payhub"

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    APPLICATIONINSIGHTS_ROLE_NAME: "p4paauth"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"

    ENABLE_AUDIT_APPENDER: "TRUE"

    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"

    JWT_TOKEN_EXPIRATION_SECONDS: "14400" # 4 HOURS
    ACCESS_ORGANIZATION_MODE_ENABLED: "true"

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string

    JWT_TOKEN_PRIVATE_KEY: jwt-private-key
    JWT_TOKEN_PUBLIC_KEY: jwt-public-key

    REDIS_HOST: cache-standalone-host
    REDIS_PASSWORD: cache-password
    MONGODB_URI: mongodb-connection-string

    MYPAY_DB_HOST: db-host
    MYPAY_DB_USER: db-mypay-login-username
    MYPAY_DB_PASSWORD: db-mypay-login-password

    MYPIVOT_DB_HOST: db-host
    MYPIVOT_DB_USER: db-mypay-login-username
    MYPIVOT_DB_PASSWORD: db-mypay-login-password

    DATA_CIPHER_P4PA_AUTH_HASH_KEY: p4pa-auth-hash-key
    DATA_CIPHER_P4PA_AUTH_ENCRYPT_PSW: p4pa-auth-encrypt-psw

    PIATTAFORMA_UNITARIA_CLIENT_SECRET: piattaforma-unitaria-client-secret

  keyvault:
    name: "p4pa-d-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # nodeSelector: {}

  # tolerations: []

#    affinity:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#          - matchExpressions:
#            - key: kubernetes.azure.com/mode
#              operator: In
#              values:
#              - user
#      podAntiAffinity:
#        preferredDuringSchedulingIgnoredDuringExecution:
#        - weight: 100
#          podAffinityTerm:
#            labelSelector:
#              matchLabels:
#                aadpodidbinding: payhub-pod-identity
#            namespaces: ["payhub"]
#            topologyKey: topology.kubernetes.io/ztwo

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
