microservice-chart:
  namespace: "payhub"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: true
    path: /p4papusil/(.*)

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  externalConfigMapValues:
    eventhub-config:
      KAFKA_CONFIG_SECURITY_PROTOCOL: p4pa-payhub-security-protocol
      KAFKA_CONFIG_SASL_MECHANISM: p4pa-payhub-sasl-mechanism
      KAFKA_TOPIC_REGISTRIES: p4pa-payhub-registries-topic

  envConfig:
    APPLICATIONINSIGHTS_ROLE_NAME: "p4pa-pu-sil"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    ENABLE_AUDIT_APPENDER: "TRUE"

    AUTH_SERVER_BASE_URL: "http://p4pa-auth-microservice-chart:8080"
    DEBT_POSITION_BASE_URL: "http://p4pa-debt-positions-microservice-chart:8080"
    ORGANIZATION_BASE_URL: "http://p4pa-organization-microservice-chart:8080"
    SEND_NOTIFICATION_BASE_URL: "http://p4pa-send-notification-microservice-chart:8080"
    PROCESS_EXECUTIONS_BASE_URL: "http://p4pa-process-executions-microservice-chart:8080"
    FILESHARE_BASE_URL: "http://p4pa-fileshare-microservice-chart:8080"
    WORKFLOW_HUB_BASE_URL: "http://p4pa-workflow-hub-microservice-chart:8080"
    CLASSIFICATION_BASE_URL: "http://p4pa-classification-microservice-chart:8080"
    PAGOPA_PAYMENTS_BASE_URL: "http://p4pa-pagopa-payments-microservice-chart:8080"

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string

    KAFKA_BINDER_BROKER: p4pa-payhub-kafka-broker
    KAFKA_REGISTRIES_PRODUCER_SASL_JAAS_CONFIG: p4pa-payhub-registries-evh-producer-jaas-config

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
