microservice-chart:
  namespace: "payhub"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: true
    path: /p4pamigration/(.*)

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  persistentVolumeClaimsMounts:
    create: true
    mounts:
      - name: share
        pvcName: mypay-fileshare-pvc
        mountPath: "/shared"

  tmpVolumeMount:
    create: true
    mounts:
      - name: tmp
        mountPath: /tmp

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    APPLICATIONINSIGHTS_ROLE_NAME: "p4pa-migration"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    ENABLE_AUDIT_APPENDER: "TRUE"

    SHARED_FOLDER_ROOT: "/shared"

    AUTH_BASE_URL: "http://p4pa-auth-microservice-chart:8080/payhub"
    ORGANIZATION_BASE_URL: "http://p4pa-organization-microservice-chart:8080"
    FILE_SHARE_BASE_URL: "http://p4pa-fileshare-microservice-chart:8080"
    PROCESS_EXECUTIONS_BASE_URL: "http://p4pa-process-executions-microservice-chart:8080"
    DEBT_POSITION_BASE_URL: "http://p4pa-debt-positions-microservice-chart:8080"


  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string
    JWT_TOKEN_PUBLIC_KEY: jwt-public-key

    AUTH_CLIENT_SECRET: piattaforma-unitaria-client-secret

    MIGRATION_DB_HOST: db-host
    MIGRATION_DB_USER: db-piattaforma-unitaria-login-username
    MIGRATION_DB_PASSWORD: db-piattaforma-unitaria-login-password

    FILE_ENCRYPT_PASSWORD: file-encrypt-password

    ZIP_MAX_COMPRESSION_RATIO: 999999