microservice-chart:
  namespace: "payhub"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: true
    path: /p4paiamsync/(.*)

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    APPLICATIONINSIGHTS_ROLE_NAME: "p4pa-iam-sync"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    ENABLE_AUDIT_APPENDER: "TRUE"

    KAFKA_CONFIG_SASL_MECHANISM: "PLAIN"
    KAFKA_CONFIG_SECURITY_PROTOCOL: "SASL_SSL"
    KAFKA_IAM_ORGANIZATIONS_TOPIC: p4pa-payhub-payments-topic
    KAFKA_IAM_USERS_TOPIC: p4pa-payhub-payments-topic

    AUTH_BASE_URL: "http://p4pa-auth-microservice-chart:8080/payhub"
    ORGANIZATION_BASE_URL: "http://p4pa-organization-microservice-chart:8080"

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string
    JWT_TOKEN_PUBLIC_KEY: jwt-public-key

    AUTH_CLIENT_SECRET: piattaforma-unitaria-client-secret

    KAFKA_IAM_ORGANIZATIONS_CONSUMER_SASL_JAAS_CONFIG: p4pa-payhub-payments-evh-consumer-jaas-config
    KAFKA_IAM_USERS_CONSUMER_SASL_JAAS_CONFIG: p4pa-payhub-payments-evh-consumer-jaas-config

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
