microservice-chart:
  namespace: "payhub"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: true
    path: /p4paorganization/(.*)

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    APPLICATIONINSIGHTS_ROLE_NAME: "p4pa-organization"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    ENABLE_AUDIT_APPENDER: "TRUE"

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string
    ORGANIZATION_DB_HOST: db-host
    ORGANIZATION_DB_USER: db-piattaforma-unitaria-login-username
    ORGANIZATION_DB_PASSWORD: db-piattaforma-unitaria-login-password
    BROKER_ENCRYPT_PASSWORD: broker-encrypt-password
    JWT_TOKEN_PUBLIC_KEY: jwt-public-key

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
