microservice-chart:
  namespace: "cittadini"

  image:
    repository: ghcr.io/pagopa/arc-be
    tag: develop-latest
    pullPolicy: Always

  ingress:
    create: true
    host: "citizen.internal.dev.cittadini.pagopa.it"
    path: /arcbe/(.*)

  resources:
    requests:
      memory: " 2048Mi"
      cpu: "1000m"
    limits:
      memory: " 2048Mi"
      cpu: "1000m"

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 15
    periodSeconds: 10
    timeoutSeconds: 2

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 15
    periodSeconds: 10
    timeoutSeconds: 2

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    JAVA_TOOL_OPTIONS: "-Xms1024m -Xmx1024m -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopaarcbe"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    ENABLE_AUDIT_APPENDER: "TRUE"
    JWT_TOKEN_EXPIRATION_SECONDS: "28800"
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    ENV: "DEV"
    AUTH_CLIENT_REDIRECT_URI: https://dev.cittadini.pagopa.it/pagamenti/auth-callback
    AUTH_ISSUER_URI: https://dev.oneid.pagopa.it
    AUTH_CLIENT_AUTHORIZATION_URI: https://dev.oneid.pagopa.it/login
    AUTH_CLIENT_TOKEN_URI: https://dev.oneid.pagopa.it/oidc/token
    AUTH_CLIENT_JWK_URI: https://dev.oneid.pagopa.it/oidc/keys

  externalConfigMapValues:
    rest-client:
      BIZ_EVENTS_PAID_NOTICE_BASE_URL: bizevents-paids-base-url
      PULL_PAYMENT_BASE_URL: pullpayment-base-url
      GPD_SERVICE_BASE_URL: gpd-service-base-url
    assistance:
      ASSISTANCE_ZENDESK_PRODUCT_ID: assistance-arc-zendesk-product-id
      ASSISTANCE_ZENDESK_ORGANIZATION: assistance-arc-zendesk-organization
      HELP_CENTER_URL: arc-help-center-url
      ZENDESK_ACTION_URL: zendesk-action-url

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string
    BIZ_EVENTS_PAID_NOTICE_SERVICE_API_KEY: pagopa-bizevents-paids-trx-apimv1-subscription-key
    PULL_PAYMENT_SERVICE_API_KEY: pagopa-pullpayment-apimv1-subscription-key
    GPD_SERVICE_API_KEY: pagopa-gpd-debt-positions-apimv1-subscription-key
    AUTH_CLIENT_ID: oneidentity-client-id
    AUTH_CLIENT_SECRET: oneidentity-client-secret
    JWT_TOKEN_PRIVATE_KEY: jwt-private-key
    JWT_TOKEN_PUBLIC_KEY: jwt-public-key
    JWT_TOKEN_ASSISTANCE_ZENDESK_PRIVATE_KEY: jwt-assistance-zendesk-private-key
    WHITE_LIST_USERS: cf-whitelist
    REDIS_HOST: cache-standalone-host
    REDIS_PASSWORD: cache-password

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}

  autoscaling:
    enable: false
  #    minReplica: 1
  #    maxReplica: 1
  #    pollingInterval: 30 # seconds
  #    cooldownPeriod: 300 # seconds
  #    triggers:
  #      - type: cpu
  #        metadata:
  #          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
  #          value: "50"

  keyvault:
    name: "arc-d-itn-cittadini-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

postman-test:
  run: true
  repoName: arc-be
  dir: postman
  collectionName: "pagopa-arc-E2E.postman_collection.json"
  envVariablesFile: "arc_DEV.postman_environment.json" #inside azdo secure files
