microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-pdnd-services
    tag: v1.0.0
    pullPolicy: Always

  ingress:
    host: "hub.internal.p4pa.pagopa.it"

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1536Mi"
      cpu: "1500m"

  autoscaling:
    enable: false

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    ENV: "PROD"
    JAVA_OPTS: >-
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=100
      -XX:+UseContainerSupport
      -XX:ActiveProcessorCount=$(nproc)
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=$[$(nproc)*2]
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/secrets/appinsights.json
      -Dcom.sun.management.jmxremote.local.only=true
      -Dcom.sun.management.jmxremote.port=3002
      -Dcom.sun.management.jmxremote.authenticate=true
      -Dcom.sun.management.jmxremote.ssl=true
      -Dcom.sun.management.jmxremote.access.file=/etc/jmx/jmx.access
      -Dcom.sun.management.jmxremote.password.file=/etc/jmx/jmx.password
      -XX:+ExitOnOutOfMemoryError
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/var/log/heapdump-${POD_NAME}.hprof
      -Xlog:gc*,safepoint:file=/var/log/gc-${POD_NAME}.log:time,uptime,level,tags:filesize=100M,filecount=5
      -XX:+PerfDisableSharedMem
      -XX:+AlwaysPreTouch
      -XX:+UseTransparentHugePages
      -XX:NativeMemoryTracking=detail
      -Djdk.nio.maxCachedBufferSize=262144
      -Djava.security.egd=file:/dev/./urandom
      -Dspring.profiles.active=prod

    #TODO edit with real env when prod is ready P4ADEV-1518
    PDND_BASE_URL: https://auth.uat.interop.pagopa.it
    PDND_ACCESS_TOKEN_AUDIENCE: auth.uat.interop.pagopa.it/client-assertion
    PDND_SERVICE_CLIENTID: 890b7ca9-b402-4dce-9e8d-9a333d22d76d
    PDND_SERVICE_KID: jxOpPRxM6oFcnnKtICqeW5l7fbxLr45IAsJ8Q9s-fK8
    PDND_SERVICE_ANPR_C003_PURPOSE_ID: 5ba1f38f-6a91-4da4-8a42-4da1aa55bfee
    PDND_SERVICE_ANPR_C030_PURPOSE_ID: 87520bd5-207a-4616-85d9-10d7bb3e88b8

    ANPR_BASE_URL: http://p4pa-mocks-microservice-chart:8080

  keyvault:
    name: "p4pa-p-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

postman-test:
  run: true
  repoName: p4pa-pdnd-services
  dir: postman
  collectionName: "p4pa-pdnd-services-E2E.postman_collection.json"
  envVariablesFile: "p4pa_PROD.postman_environment.json" #inside azdo secure files