microservice-chart:
  namespace: "payhub"

  envConfig:
    APP: basic
    MY_APP_COLOR: "green"

  envSecret:
    MY_KV_SECRET: argocd-server-url

  image:
    repository: ghcr.io/pagopa/devops-java-springboot-color
    tag: latest
    pullPolicy: Always

  tmpVolumeMount:
    create: true
    mounts:
      - name: tmp
        mountPath: /tmp
      - name: logs
        mountPath: /app/logs

  livenessProbe:
    httpGet:
      path: /status/live
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /status/ready
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 6
    periodSeconds: 10

  ingress:
    create: true
    host: hub.internal.dev.p4pa.pagopa.it
    path: /payhub/two-color(/|$)(.*)
    rewriteTarget: /$2
    servicePort: 8080

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "512Mi"
      cpu: "300m"

