microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-debt-positions
    tag: develop-latest
    pullPolicy: Always

  ingress:
    host: "hub.internal.dev.p4pa.pagopa.it"

  resources:
    requests:
      memory: "512Mi"
      cpu: "350m"
    limits:
      memory: "1024Mi"
      cpu: "750m"

  autoscaling:
    enable: false
  #    minReplica: 1
  #    maxReplica: 1
  #    pollingInterval: 30 # seconds
  #    cooldownPeriod: 300 # seconds
  #    triggers:
  #      - type: cpu
  #        metadata:
  #          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
  #          value: "70"

  envConfig:
    ENV: "DEV"
    JAVA_TOOL_OPTIONS: >-
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=4
      -XX:InitialRAMPercentage=60.0
      -XX:MaxRAMPercentage=70.0
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=200
      -XX:+UseContainerSupport
      -XX:+ShowCodeDetailsInExceptionMessages
      -XX:+EnableDynamicAgentLoading
      -Dspring.profiles.active=dev
      -agentlib:jdwp=transport=dt_socket,server=y,address=*:8001,suspend=n
      -Dcom.sun.management.jmxremote
      -Dcom.sun.management.jmxremote.port=3002
      -Dcom.sun.management.jmxremote.rmi.port=3003
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false
      -Dcom.sun.management.jmxremote.local.only=false
      -Djava.rmi.server.hostname=127.0.0.1 
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json 

    LOG_LEVEL_PAGOPA: "DEBUG"
    FEATURE_ORGANIZATION_PIVA_CHECK: false

  keyvault:
    name: "p4pa-d-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

postman-test:
  run: true
  repoName: p4pa-debt-positions
  dir: postman
  collectionName: "p4pa-debt-positions-E2E.postman_collection.json"
  envVariablesFile: "p4pa_DEV.postman_environment.json" #inside azdo secure files
