microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-pu-sil
    tag: v1.0.0
    pullPolicy: Always

  ingress:
    host: "hub.internal.p4pa.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "750m"

  autoscaling:
    enable: false

  envConfig:
    ENV: "PROD"
    JAVA_TOOL_OPTIONS: >-
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=$[$(nproc)*2]
      -XX:InitialRAMPercentage=75.0
      -XX:MaxRAMPercentage=85.0
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=100
      -XX:+UseContainerSupport
      -XX:ActiveProcessorCount=$(nproc)
      -XX:+ExitOnOutOfMemoryError
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/var/log/heapdump-${POD_NAME}.hprof
      -Xlog:gc*,safepoint:file=/var/log/gc-${POD_NAME}.log:time,uptime,level,tags:filesize=100M,filecount=5
      -XX:+PerfDisableSharedMem
      -XX:+AlwaysPreTouch
      -XX:+UseTransparentHugePages
      -XX:NativeMemoryTracking=detail
      -Djdk.nio.maxCachedBufferSize=262144
      -Djava.security.egd=file:/dev/./urandom
      -Dspring.profiles.active=prod
      -Dcom.sun.management.jmxremote.local.only=true
      -Dcom.sun.management.jmxremote.port=3002
      -Dcom.sun.management.jmxremote.authenticate=true
      -Dcom.sun.management.jmxremote.ssl=true
      -Dcom.sun.management.jmxremote.access.file=/etc/jmx/jmx.access
      -Dcom.sun.management.jmxremote.password.file=/etc/jmx/jmx.password
      -Djava.rmi.server.hostname=127.0.0.1 
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json
  
    SIL_WSDL_BASE_URL: "https://hub.internal.p4pa.pagopa.it/p4papusil"
    PUBLIC_BASE_URL_FILESHARE: "https://api.p4pa.pagopa.it/pu/fileshare"
    PUBLIC_BASE_URL_PU_SIL: "https://api.p4pa.pagopa.it/pu/sil"
    PAGOPA_NODE_CHECKOUT_BASE_URL: "https://api.platform.pagopa.it/checkout/ec/v1"

    # The following URLs are used by the Checkout service to redirect the user after payment
    CHECKOUT_DEFAULT_CALLBACK_URL_OK: "https://p4pa.pagopa.it/piattaformaunitaria/checkout-callback/ok"
    CHECKOUT_DEFAULT_CALLBACK_URL_KO: "https://p4pa.pagopa.it/piattaformaunitaria/checkout-callback/ko"
    CHECKOUT_DEFAULT_CALLBACK_URL_CANCEL: "https://p4pa.pagopa.it/piattaformaunitaria/checkout-callback/cancel"
  keyvault:
    name: "p4pa-p-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
