microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-pu-sil
    tag: develop-latest@sha256:42ba59263e0e4bde5299ad44f7d18d65843325582844a380bb2342174525cd93
    pullPolicy: Always

  ingress:
    host: "hub.internal.dev.p4pa.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "4Gi"
      cpu: "300m"

  autoscaling:
    enable: false

  envConfig:
    ENV: "DEV"

    JAVA_TOOL_OPTIONS: >-
      -Djava.util.concurrent.ForkJoinPool.common.parallelism=4
      -XX:InitialRAMPercentage=60.0
      -XX:MaxRAMPercentage=70.0
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=200
      -XX:+UseContainerSupport
      -XX:+ShowCodeDetailsInExceptionMessages
      -XX:+EnableDynamicAgentLoading
      -Dspring.profiles.active=dev
      -agentlib:jdwp=transport=dt_socket,server=y,address=*:8001,suspend=n
      -Dcom.sun.management.jmxremote
      -Dcom.sun.management.jmxremote.port=3002
      -Dcom.sun.management.jmxremote.rmi.port=3003
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false
      -Dcom.sun.management.jmxremote.local.only=false
      -Djava.rmi.server.hostname=127.0.0.1 
      -javaagent:/app/applicationinsights-agent.jar
      -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json 
    
    SIL_WSDL_BASE_URL: "https://hub.internal.dev.p4pa.pagopa.it/p4papusil"
    PUBLIC_BASE_URL_FILESHARE: "https://api.dev.p4pa.pagopa.it/pu/fileshare"
    PUBLIC_BASE_URL_PU_SIL: "https://api.dev.p4pa.pagopa.it/pu/sil"
    PAGOPA_NODE_CHECKOUT_BASE_URL: "https://api.uat.platform.pagopa.it/checkout/ec/v1"

    # The following URLs are used by the Checkout service to redirect the user after payment
    CHECKOUT_DEFAULT_CALLBACK_URL_OK: "https://dev.p4pa.pagopa.it/piattaformaunitaria/checkout-callback/ok"
    CHECKOUT_DEFAULT_CALLBACK_URL_KO: "https://dev.p4pa.pagopa.it/piattaformaunitaria/checkout-callback/ko"
    CHECKOUT_DEFAULT_CALLBACK_URL_CANCEL: "https://dev.p4pa.pagopa.it/piattaformaunitaria/checkout-callback/cancel"

  keyvault:
    name: "p4pa-d-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
