microservice-chart:
  image:
    repository: ghcr.io/pagopa/p4pa-workflow-hub
    tag: develop-latest
    pullPolicy: Always

  ingress:
    host: "hub.internal.dev.p4pa.pagopa.it"

  resources:
    requests:
      memory: "1Gi"
      cpu: "750m"
    limits:
      memory: "1Gi"
      cpu: "750m"

  autoscaling:
    enable: false

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    ENV: "DEV"
    JAVA_TOOL_OPTIONS: "-Xms384m -Xmx384m -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

    TEMPORAL_SERVER_ENABLE_HTTPS: "true"
    TEMPORAL_SERVER_HOST: "api.temporal.internal.dev.p4pa.pagopa.it"
    TEMPORAL_SERVER_PORT: "443"

    MAIL_HOST: "smtp.ethereal.email"

  keyvault:
    name: "p4pa-d-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

postman-test:
  run: true
  repoName: p4pa-workflow-hub
  dir: postman
  collectionName: "p4pa-workflow-hub-E2E.postman_collection.json"
  envVariablesFile: "p4pa_DEV.postman_environment.json" #inside azdo secure files
